################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
ASM_DEPS := 
C_DEPS := 
EXECUTABLES := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
subsystems \
subsystems/sensors \
subsystems/radio_control \
subsystems/navigation \
subsystems/ins \
subsystems/gps \
subsystems/datalink \
subsystems/ahrs \
. \
modules/openlog \
modules/digital_cam \
mcu_periph \
math \
firmwares/fixedwing/stabilization \
firmwares/fixedwing \
firmwares/fixedwing/guidance \
customized_makefile/subsystems \
customized_makefile/subsystems/sensors \
customized_makefile/subsystems/radio_control \
customized_makefile/subsystems/navigation \
customized_makefile/subsystems/ins \
customized_makefile/subsystems/gps \
customized_makefile/subsystems/datalink \
customized_makefile/subsystems/ahrs \
customized_makefile \
customized_makefile/modules/openlog \
customized_makefile/modules/digital_cam \
customized_makefile/mcu_periph \
customized_makefile/math \
customized_makefile/firmwares/fixedwing/stabilization \
customized_makefile/firmwares/fixedwing \
customized_makefile/firmwares/fixedwing/guidance \
customized_makefile/arch/sim/subsystems \
customized_makefile/arch/sim/subsystems/radio_control \
customized_makefile/arch/sim/subsystems/actuators \
customized_makefile/arch/sim \
customized_makefile/arch/sim/peripherals \
customized_makefile/arch/sim/mcu_periph \
boards/DEBUG/tests \
boards/DEBUG/subsystems \
boards/DEBUG/subsystems/sensors \
boards/DEBUG/subsystems/radio_control \
boards/DEBUG/subsystems/navigation \
boards/DEBUG/subsystems/ins \
boards/DEBUG/subsystems/gps \
boards/DEBUG/subsystems/datalink \
boards/DEBUG/subsystems/ahrs \
boards/DEBUG \
boards/DEBUG/modules/openlog \
boards/DEBUG/modules/digital_cam \
boards/DEBUG/mcu_periph \
boards/DEBUG/math \
boards/DEBUG/firmwares/fixedwing/stabilization \
boards/DEBUG/firmwares/fixedwing/guidance \
boards/DEBUG/firmwares/fixedwing \
boards/DEBUG/arch/sim/subsystems \
boards/DEBUG/arch/sim/subsystems/radio_control \
boards/DEBUG/arch/sim/subsystems/actuators \
boards/DEBUG/arch/sim \
boards/DEBUG/arch/sim/peripherals \
boards/DEBUG/arch/sim/mcu_periph \
arch/sim/subsystems \
arch/sim/subsystems/radio_control \
arch/sim/subsystems/actuators \
arch/sim \
arch/sim/peripherals \
arch/sim/mcu_periph \
SIS_DEBUG/tests \
RELEASE/mcu_periph \
BOARD_TEST/tests \
BOARD_TEST/mcu_periph \

